apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwriting
  namespace: insurancecontract
  labels:
    app: underwriting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: underwriting
  template:
    metadata:
      labels:
        app: underwriting
    spec:
      containers:
        - name: underwriting
          image: 095661863019.dkr.ecr.ap-northeast-2.amazonaws.com/underwriting:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5