apiVersion: v1
kind: Service
metadata:
  name: underwriting
  namespace: insurancecontract
  labels:
    app: underwriting
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: underwriting