server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: subscription
          uri: http://localhost:8081
          predicates:
            - Path=/subscriptions/** 
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/payments/** 
        - id: underwriting
          uri: http://localhost:8083
          predicates:
            - Path=/underwritings/** 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path= /subsciptionViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: subscription
          uri: http://subscription:8080
          predicates:
            - Path=/subscriptions/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: underwriting
          uri: http://underwriting:8080
          predicates:
            - Path=/underwritings/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /subsciptionViews/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080